// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDs3Bf5_nLOp9qWgJu88pwv7_ogN97HyJE',
    appId: '1:1087331266875:web:d0002720fca3c1970ac71e',
    messagingSenderId: '1087331266875',
    projectId: 'notesapp-flu--project',
    authDomain: 'notesapp-flu--project.firebaseapp.com',
    storageBucket: 'notesapp-flu--project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQs9zlZutoMVWZPWUqqFsUaKD5NGl0KCc',
    appId: '1:1087331266875:android:c411bb7b494e68620ac71e',
    messagingSenderId: '1087331266875',
    projectId: 'notesapp-flu--project',
    storageBucket: 'notesapp-flu--project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlNdfug4j_zfik8ymtZnaNzEimpT7-E1k',
    appId: '1:1087331266875:ios:30b7c3f53fff28380ac71e',
    messagingSenderId: '1087331266875',
    projectId: 'notesapp-flu--project',
    storageBucket: 'notesapp-flu--project.appspot.com',
    iosBundleId: 'id.sentravion.notesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlNdfug4j_zfik8ymtZnaNzEimpT7-E1k',
    appId: '1:1087331266875:ios:aac6332dfc142fb90ac71e',
    messagingSenderId: '1087331266875',
    projectId: 'notesapp-flu--project',
    storageBucket: 'notesapp-flu--project.appspot.com',
    iosBundleId: 'id.sentravion.notesApp.RunnerTests',
  );
}
